### ISSUE TITLE
create :eventDateTime datatype or specify date/time property ranges in xsd or owl-time

### ISSUE THREAD

**Issue by marshallduval** [PREMIS-OWL-Revision-Team/premis-owl#52]

**Comment by BertrandCaron** [comment]
For event date and time, we recommend using prov:startedAtTime / prov:endedAtTime, whose range is xsd:dateTime.

We will specify the range of premis:hasDeterminationDate to be xsd:dateTime. Nevertheless, for premis:endDate / premis:startDate, the group felt that the range should stay rdfs:Literal because it should accomodate uncertainty and open dates.
