### ISSUE TITLE
drop redundant :hasNote subproperties

### ISSUE THREAD

**Issue by marshallduval** [PREMIS-OWL-Revision-Team/premis-owl#53]

**Comment by BertrandCaron** [comment]
Dear Marshall,

All properties whose range was expected to be free text were declared subproperties of premis:hasNote. These were defined because their meaning was more precise than premis:hasNote, and/or because a premis:hasNote property was already defined to express the content of another PREMIS semantic unit (we realize that some of the decisions we took may be a bit strange if readers don't know that the ontology is meant to be as faithful as possible to the PREMIS Data Dictionary as it is now in v. 3).

Could you please elaborate why you think they are redundant?

Best,

B. Caron
